api_platform:
    title: Car Rental API
    version: 1.0.0
    description: 'API de gestion de location de voitures avec authentification JWT'
    
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
