
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    container_name: car_rental_db
    environment:
      POSTGRES_DB: car_rental_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "car_rental_db", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
###< doctrine/doctrine-bundle ###

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car_rental_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://app:app@database:5432/car_rental_db?serverVersion=16&charset=utf8
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: change_me_in_production
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    command: php -S 0.0.0.0:8000 -t public

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
